/**
 * GENERATED by scripts/import-frontier-plates.mjs — do not edit by hand.
 *
 * Generated campaign artwork (provenance: generated-campaign), owner-supplied
 * 2026-08-13. Artwork, never photography. The fabricated "EST. 2024" date and the
 * "TRUSTED BY GENERATIONS" strip were excised at import and exist in no output.
 * Full provenance: public/media/frontier/manifest.json
 */

import type { MensDemoAsset } from './mens-demo-media.generated'

export const FRONTIER_PLATE_MEDIA: Record<string, MensDemoAsset> = {
  'corral-wide': {
    poster: '/media/frontier/corral-wide-1672.webp',
    avifSrcSet:
      '/media/frontier/corral-wide-640.avif 640w, /media/frontier/corral-wide-960.avif 960w, /media/frontier/corral-wide-1440.avif 1440w, /media/frontier/corral-wide-1672.avif 1672w',
    webpSrcSet:
      '/media/frontier/corral-wide-640.webp 640w, /media/frontier/corral-wide-960.webp 960w, /media/frontier/corral-wide-1440.webp 1440w, /media/frontier/corral-wide-1672.webp 1672w',
    intrinsicWidth: 1672,
    intrinsicHeight: 941,
  },
  storefront: {
    poster: '/media/frontier/storefront-1122.webp',
    avifSrcSet:
      '/media/frontier/storefront-480.avif 480w, /media/frontier/storefront-720.avif 720w, /media/frontier/storefront-1122.avif 1122w',
    webpSrcSet:
      '/media/frontier/storefront-480.webp 480w, /media/frontier/storefront-720.webp 720w, /media/frontier/storefront-1122.webp 1122w',
    intrinsicWidth: 1122,
    intrinsicHeight: 1402,
  },
  'ranch-road': {
    poster: '/media/frontier/ranch-road-960.webp',
    avifSrcSet:
      '/media/frontier/ranch-road-480.avif 480w, /media/frontier/ranch-road-720.avif 720w, /media/frontier/ranch-road-960.avif 960w',
    webpSrcSet:
      '/media/frontier/ranch-road-480.webp 480w, /media/frontier/ranch-road-720.webp 720w, /media/frontier/ranch-road-960.webp 960w',
    intrinsicWidth: 960,
    intrinsicHeight: 828,
  },
  'craft-detail': {
    poster: '/media/frontier/craft-detail-550.webp',
    avifSrcSet:
      '/media/frontier/craft-detail-480.avif 480w, /media/frontier/craft-detail-550.avif 550w',
    webpSrcSet:
      '/media/frontier/craft-detail-480.webp 480w, /media/frontier/craft-detail-550.webp 550w',
    intrinsicWidth: 550,
    intrinsicHeight: 310,
  },
  'heritage-truck': {
    poster: '/media/frontier/heritage-truck-550.webp',
    avifSrcSet:
      '/media/frontier/heritage-truck-480.avif 480w, /media/frontier/heritage-truck-550.avif 550w',
    webpSrcSet:
      '/media/frontier/heritage-truck-480.webp 480w, /media/frontier/heritage-truck-550.webp 550w',
    intrinsicWidth: 550,
    intrinsicHeight: 282,
  },
  'campaign-backdrop': {
    poster: '/media/frontier/campaign-backdrop-1672.webp',
    avifSrcSet:
      '/media/frontier/campaign-backdrop-768.avif 768w, /media/frontier/campaign-backdrop-1280.avif 1280w, /media/frontier/campaign-backdrop-1672.avif 1672w',
    webpSrcSet:
      '/media/frontier/campaign-backdrop-768.webp 768w, /media/frontier/campaign-backdrop-1280.webp 1280w, /media/frontier/campaign-backdrop-1672.webp 1672w',
    intrinsicWidth: 1672,
    intrinsicHeight: 941,
  },
  'legacy-boots': {
    poster: '/media/frontier/legacy-boots-550.webp',
    avifSrcSet:
      '/media/frontier/legacy-boots-480.avif 480w, /media/frontier/legacy-boots-550.avif 550w',
    webpSrcSet:
      '/media/frontier/legacy-boots-480.webp 480w, /media/frontier/legacy-boots-550.webp 550w',
    intrinsicWidth: 550,
    intrinsicHeight: 262,
  },
}
