/**
 * GENERATED by scripts/import-mens-demo.mjs — do not edit by hand.
 * Responsive encodings of the men's demo reference imagery in assets/source/mens-reference/.
 */

export type MensDemoAsset = {
  readonly poster: string
  readonly avifSrcSet: string
  readonly webpSrcSet: string
  readonly intrinsicWidth: number
  readonly intrinsicHeight: number
}

export const MENS_DEMO_MEDIA: Record<string, MensDemoAsset> = {
  'denim-jacket-hero': {
    poster: '/media/mens-demo/denim-jacket-hero-400.webp',
    avifSrcSet: '/media/mens-demo/denim-jacket-hero-400.avif 400w',
    webpSrcSet: '/media/mens-demo/denim-jacket-hero-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'denim-jacket-saddle': {
    poster: '/media/mens-demo/denim-jacket-saddle-536.webp',
    avifSrcSet:
      '/media/mens-demo/denim-jacket-saddle-480.avif 480w, /media/mens-demo/denim-jacket-saddle-536.avif 536w',
    webpSrcSet:
      '/media/mens-demo/denim-jacket-saddle-480.webp 480w, /media/mens-demo/denim-jacket-saddle-536.webp 536w',
    intrinsicWidth: 536,
    intrinsicHeight: 670,
  },
  'dark-rigid-jean-flat': {
    poster: '/media/mens-demo/dark-rigid-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-flat-480.avif 480w, /media/mens-demo/dark-rigid-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-flat-480.webp 480w, /media/mens-demo/dark-rigid-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'dark-rigid-jean-side': {
    poster: '/media/mens-demo/dark-rigid-jean-side-720.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-side-480.avif 480w, /media/mens-demo/dark-rigid-jean-side-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-side-480.webp 480w, /media/mens-demo/dark-rigid-jean-side-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'dark-rigid-jean-macro': {
    poster: '/media/mens-demo/dark-rigid-jean-macro-720.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-macro-480.avif 480w, /media/mens-demo/dark-rigid-jean-macro-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-macro-480.webp 480w, /media/mens-demo/dark-rigid-jean-macro-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 720,
  },
  'mid-wash-jean-flat': {
    poster: '/media/mens-demo/mid-wash-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-flat-480.avif 480w, /media/mens-demo/mid-wash-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-flat-480.webp 480w, /media/mens-demo/mid-wash-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'mid-wash-jean-model': {
    poster: '/media/mens-demo/mid-wash-jean-model-540.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-model-480.avif 480w, /media/mens-demo/mid-wash-jean-model-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-model-480.webp 480w, /media/mens-demo/mid-wash-jean-model-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'mid-wash-jean-front': {
    poster: '/media/mens-demo/mid-wash-jean-front-720.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-front-480.avif 480w, /media/mens-demo/mid-wash-jean-front-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-front-480.webp 480w, /media/mens-demo/mid-wash-jean-front-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'mid-wash-jean-hem': {
    poster: '/media/mens-demo/mid-wash-jean-hem-400.webp',
    avifSrcSet: '/media/mens-demo/mid-wash-jean-hem-400.avif 400w',
    webpSrcSet: '/media/mens-demo/mid-wash-jean-hem-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'light-wash-jean-flat': {
    poster: '/media/mens-demo/light-wash-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/light-wash-jean-flat-480.avif 480w, /media/mens-demo/light-wash-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/light-wash-jean-flat-480.webp 480w, /media/mens-demo/light-wash-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'light-wash-jean-model': {
    poster: '/media/mens-demo/light-wash-jean-model-920.webp',
    avifSrcSet:
      '/media/mens-demo/light-wash-jean-model-480.avif 480w, /media/mens-demo/light-wash-jean-model-920.avif 920w',
    webpSrcSet:
      '/media/mens-demo/light-wash-jean-model-480.webp 480w, /media/mens-demo/light-wash-jean-model-920.webp 920w',
    intrinsicWidth: 920,
    intrinsicHeight: 1150,
  },
  'light-wash-jean-hem': {
    poster: '/media/mens-demo/light-wash-jean-hem-400.webp',
    avifSrcSet: '/media/mens-demo/light-wash-jean-hem-400.avif 400w',
    webpSrcSet: '/media/mens-demo/light-wash-jean-hem-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'bootcut-jean-model': {
    poster: '/media/mens-demo/bootcut-jean-model-720.webp',
    avifSrcSet:
      '/media/mens-demo/bootcut-jean-model-480.avif 480w, /media/mens-demo/bootcut-jean-model-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/bootcut-jean-model-480.webp 480w, /media/mens-demo/bootcut-jean-model-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'bootcut-jean-hem': {
    poster: '/media/mens-demo/bootcut-jean-hem-400.webp',
    avifSrcSet: '/media/mens-demo/bootcut-jean-hem-400.avif 400w',
    webpSrcSet: '/media/mens-demo/bootcut-jean-hem-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'bootcut-jean-drape': {
    poster: '/media/mens-demo/bootcut-jean-drape-536.webp',
    avifSrcSet:
      '/media/mens-demo/bootcut-jean-drape-480.avif 480w, /media/mens-demo/bootcut-jean-drape-536.avif 536w',
    webpSrcSet:
      '/media/mens-demo/bootcut-jean-drape-480.webp 480w, /media/mens-demo/bootcut-jean-drape-536.webp 536w',
    intrinsicWidth: 536,
    intrinsicHeight: 670,
  },
  'khaki-jean-flat': {
    poster: '/media/mens-demo/khaki-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/khaki-jean-flat-480.avif 480w, /media/mens-demo/khaki-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/khaki-jean-flat-480.webp 480w, /media/mens-demo/khaki-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'khaki-jean-model': {
    poster: '/media/mens-demo/khaki-jean-model-920.webp',
    avifSrcSet:
      '/media/mens-demo/khaki-jean-model-480.avif 480w, /media/mens-demo/khaki-jean-model-920.avif 920w',
    webpSrcSet:
      '/media/mens-demo/khaki-jean-model-480.webp 480w, /media/mens-demo/khaki-jean-model-920.webp 920w',
    intrinsicWidth: 920,
    intrinsicHeight: 1150,
  },
  'khaki-jean-pocket': {
    poster: '/media/mens-demo/khaki-jean-pocket-720.webp',
    avifSrcSet:
      '/media/mens-demo/khaki-jean-pocket-480.avif 480w, /media/mens-demo/khaki-jean-pocket-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/khaki-jean-pocket-480.webp 480w, /media/mens-demo/khaki-jean-pocket-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 720,
  },
  'khaki-jean-side': {
    poster: '/media/mens-demo/khaki-jean-side-720.webp',
    avifSrcSet:
      '/media/mens-demo/khaki-jean-side-480.avif 480w, /media/mens-demo/khaki-jean-side-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/khaki-jean-side-480.webp 480w, /media/mens-demo/khaki-jean-side-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'stripe-shirt-flat': {
    poster: '/media/mens-demo/stripe-shirt-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/stripe-shirt-flat-480.avif 480w, /media/mens-demo/stripe-shirt-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/stripe-shirt-flat-480.webp 480w, /media/mens-demo/stripe-shirt-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'saddle-belt-flat': {
    poster: '/media/mens-demo/saddle-belt-flat-400.webp',
    avifSrcSet: '/media/mens-demo/saddle-belt-flat-400.avif 400w',
    webpSrcSet: '/media/mens-demo/saddle-belt-flat-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'saddle-belt-worn': {
    poster: '/media/mens-demo/saddle-belt-worn-720.webp',
    avifSrcSet:
      '/media/mens-demo/saddle-belt-worn-480.avif 480w, /media/mens-demo/saddle-belt-worn-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/saddle-belt-worn-480.webp 480w, /media/mens-demo/saddle-belt-worn-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'ostrich-belt-flat': {
    poster: '/media/mens-demo/ostrich-belt-flat-400.webp',
    avifSrcSet: '/media/mens-demo/ostrich-belt-flat-400.avif 400w',
    webpSrcSet: '/media/mens-demo/ostrich-belt-flat-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'leather-duffel': {
    poster: '/media/mens-demo/leather-duffel-400.webp',
    avifSrcSet: '/media/mens-demo/leather-duffel-400.avif 400w',
    webpSrcSet: '/media/mens-demo/leather-duffel-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'campaign-boot-pull': {
    poster: '/media/mens-demo/campaign-boot-pull-400.webp',
    avifSrcSet: '/media/mens-demo/campaign-boot-pull-400.avif 400w',
    webpSrcSet: '/media/mens-demo/campaign-boot-pull-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'campaign-gravel': {
    poster: '/media/mens-demo/campaign-gravel-400.webp',
    avifSrcSet: '/media/mens-demo/campaign-gravel-400.avif 400w',
    webpSrcSet: '/media/mens-demo/campaign-gravel-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
}
