/**
 * GENERATED by scripts/import-mens-demo.mjs — do not edit by hand.
 * Responsive encodings of the men's demo reference imagery in assets/source/mens-reference/.
 */

export type MensDemoAsset = {
  readonly poster: string
  readonly avifSrcSet: string
  readonly webpSrcSet: string
  readonly intrinsicWidth: number
  readonly intrinsicHeight: number
}

export const MENS_DEMO_MEDIA: Record<string, MensDemoAsset> = {
  'denim-jacket-hero': {
    poster: '/media/mens-demo/denim-jacket-hero-400.webp',
    avifSrcSet: '/media/mens-demo/denim-jacket-hero-400.avif 400w',
    webpSrcSet: '/media/mens-demo/denim-jacket-hero-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'denim-jacket-saddle': {
    poster: '/media/mens-demo/denim-jacket-saddle-536.webp',
    avifSrcSet:
      '/media/mens-demo/denim-jacket-saddle-480.avif 480w, /media/mens-demo/denim-jacket-saddle-536.avif 536w',
    webpSrcSet:
      '/media/mens-demo/denim-jacket-saddle-480.webp 480w, /media/mens-demo/denim-jacket-saddle-536.webp 536w',
    intrinsicWidth: 536,
    intrinsicHeight: 670,
  },
  'dark-rigid-jean-flat': {
    poster: '/media/mens-demo/dark-rigid-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-flat-480.avif 480w, /media/mens-demo/dark-rigid-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-flat-480.webp 480w, /media/mens-demo/dark-rigid-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'dark-rigid-jean-side': {
    poster: '/media/mens-demo/dark-rigid-jean-side-720.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-side-480.avif 480w, /media/mens-demo/dark-rigid-jean-side-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-side-480.webp 480w, /media/mens-demo/dark-rigid-jean-side-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'dark-rigid-jean-macro': {
    poster: '/media/mens-demo/dark-rigid-jean-macro-720.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-macro-480.avif 480w, /media/mens-demo/dark-rigid-jean-macro-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-macro-480.webp 480w, /media/mens-demo/dark-rigid-jean-macro-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 720,
  },
  'mid-wash-jean-flat': {
    poster: '/media/mens-demo/mid-wash-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-flat-480.avif 480w, /media/mens-demo/mid-wash-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-flat-480.webp 480w, /media/mens-demo/mid-wash-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'mid-wash-jean-model': {
    poster: '/media/mens-demo/mid-wash-jean-model-540.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-model-480.avif 480w, /media/mens-demo/mid-wash-jean-model-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-model-480.webp 480w, /media/mens-demo/mid-wash-jean-model-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'mid-wash-jean-front': {
    poster: '/media/mens-demo/mid-wash-jean-front-720.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-front-480.avif 480w, /media/mens-demo/mid-wash-jean-front-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-front-480.webp 480w, /media/mens-demo/mid-wash-jean-front-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'mid-wash-jean-hem': {
    poster: '/media/mens-demo/mid-wash-jean-hem-400.webp',
    avifSrcSet: '/media/mens-demo/mid-wash-jean-hem-400.avif 400w',
    webpSrcSet: '/media/mens-demo/mid-wash-jean-hem-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'light-wash-jean-flat': {
    poster: '/media/mens-demo/light-wash-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/light-wash-jean-flat-480.avif 480w, /media/mens-demo/light-wash-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/light-wash-jean-flat-480.webp 480w, /media/mens-demo/light-wash-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'light-wash-jean-model': {
    poster: '/media/mens-demo/light-wash-jean-model-920.webp',
    avifSrcSet:
      '/media/mens-demo/light-wash-jean-model-480.avif 480w, /media/mens-demo/light-wash-jean-model-920.avif 920w',
    webpSrcSet:
      '/media/mens-demo/light-wash-jean-model-480.webp 480w, /media/mens-demo/light-wash-jean-model-920.webp 920w',
    intrinsicWidth: 920,
    intrinsicHeight: 1150,
  },
  'light-wash-jean-hem': {
    poster: '/media/mens-demo/light-wash-jean-hem-400.webp',
    avifSrcSet: '/media/mens-demo/light-wash-jean-hem-400.avif 400w',
    webpSrcSet: '/media/mens-demo/light-wash-jean-hem-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'bootcut-jean-model': {
    poster: '/media/mens-demo/bootcut-jean-model-720.webp',
    avifSrcSet:
      '/media/mens-demo/bootcut-jean-model-480.avif 480w, /media/mens-demo/bootcut-jean-model-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/bootcut-jean-model-480.webp 480w, /media/mens-demo/bootcut-jean-model-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'bootcut-jean-hem': {
    poster: '/media/mens-demo/bootcut-jean-hem-400.webp',
    avifSrcSet: '/media/mens-demo/bootcut-jean-hem-400.avif 400w',
    webpSrcSet: '/media/mens-demo/bootcut-jean-hem-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'bootcut-jean-drape': {
    poster: '/media/mens-demo/bootcut-jean-drape-536.webp',
    avifSrcSet:
      '/media/mens-demo/bootcut-jean-drape-480.avif 480w, /media/mens-demo/bootcut-jean-drape-536.avif 536w',
    webpSrcSet:
      '/media/mens-demo/bootcut-jean-drape-480.webp 480w, /media/mens-demo/bootcut-jean-drape-536.webp 536w',
    intrinsicWidth: 536,
    intrinsicHeight: 670,
  },
  'khaki-jean-flat': {
    poster: '/media/mens-demo/khaki-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/khaki-jean-flat-480.avif 480w, /media/mens-demo/khaki-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/khaki-jean-flat-480.webp 480w, /media/mens-demo/khaki-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'khaki-jean-model': {
    poster: '/media/mens-demo/khaki-jean-model-920.webp',
    avifSrcSet:
      '/media/mens-demo/khaki-jean-model-480.avif 480w, /media/mens-demo/khaki-jean-model-920.avif 920w',
    webpSrcSet:
      '/media/mens-demo/khaki-jean-model-480.webp 480w, /media/mens-demo/khaki-jean-model-920.webp 920w',
    intrinsicWidth: 920,
    intrinsicHeight: 1150,
  },
  'khaki-jean-pocket': {
    poster: '/media/mens-demo/khaki-jean-pocket-720.webp',
    avifSrcSet:
      '/media/mens-demo/khaki-jean-pocket-480.avif 480w, /media/mens-demo/khaki-jean-pocket-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/khaki-jean-pocket-480.webp 480w, /media/mens-demo/khaki-jean-pocket-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 720,
  },
  'khaki-jean-side': {
    poster: '/media/mens-demo/khaki-jean-side-720.webp',
    avifSrcSet:
      '/media/mens-demo/khaki-jean-side-480.avif 480w, /media/mens-demo/khaki-jean-side-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/khaki-jean-side-480.webp 480w, /media/mens-demo/khaki-jean-side-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'stripe-shirt-flat': {
    poster: '/media/mens-demo/stripe-shirt-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/stripe-shirt-flat-480.avif 480w, /media/mens-demo/stripe-shirt-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/stripe-shirt-flat-480.webp 480w, /media/mens-demo/stripe-shirt-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'saddle-belt-flat': {
    poster: '/media/mens-demo/saddle-belt-flat-400.webp',
    avifSrcSet: '/media/mens-demo/saddle-belt-flat-400.avif 400w',
    webpSrcSet: '/media/mens-demo/saddle-belt-flat-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'saddle-belt-worn': {
    poster: '/media/mens-demo/saddle-belt-worn-720.webp',
    avifSrcSet:
      '/media/mens-demo/saddle-belt-worn-480.avif 480w, /media/mens-demo/saddle-belt-worn-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/saddle-belt-worn-480.webp 480w, /media/mens-demo/saddle-belt-worn-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'ostrich-belt-flat': {
    poster: '/media/mens-demo/ostrich-belt-flat-400.webp',
    avifSrcSet: '/media/mens-demo/ostrich-belt-flat-400.avif 400w',
    webpSrcSet: '/media/mens-demo/ostrich-belt-flat-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'leather-duffel': {
    poster: '/media/mens-demo/leather-duffel-400.webp',
    avifSrcSet: '/media/mens-demo/leather-duffel-400.avif 400w',
    webpSrcSet: '/media/mens-demo/leather-duffel-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'campaign-boot-pull': {
    poster: '/media/mens-demo/campaign-boot-pull-400.webp',
    avifSrcSet: '/media/mens-demo/campaign-boot-pull-400.avif 400w',
    webpSrcSet: '/media/mens-demo/campaign-boot-pull-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'campaign-gravel': {
    poster: '/media/mens-demo/campaign-gravel-400.webp',
    avifSrcSet: '/media/mens-demo/campaign-gravel-400.avif 400w',
    webpSrcSet: '/media/mens-demo/campaign-gravel-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'floor-white-jean-worn': {
    poster: '/media/mens-demo/floor-white-jean-worn-920.webp',
    avifSrcSet:
      '/media/mens-demo/floor-white-jean-worn-480.avif 480w, /media/mens-demo/floor-white-jean-worn-920.avif 920w',
    webpSrcSet:
      '/media/mens-demo/floor-white-jean-worn-480.webp 480w, /media/mens-demo/floor-white-jean-worn-920.webp 920w',
    intrinsicWidth: 920,
    intrinsicHeight: 1150,
  },
  'floor-dark-jean-back': {
    poster: '/media/mens-demo/floor-dark-jean-back-720.webp',
    avifSrcSet:
      '/media/mens-demo/floor-dark-jean-back-480.avif 480w, /media/mens-demo/floor-dark-jean-back-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/floor-dark-jean-back-480.webp 480w, /media/mens-demo/floor-dark-jean-back-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'floor-black-boots': {
    poster: '/media/mens-demo/floor-black-boots-400.webp',
    avifSrcSet: '/media/mens-demo/floor-black-boots-400.avif 400w',
    webpSrcSet: '/media/mens-demo/floor-black-boots-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'floor-dark-hem-boot': {
    poster: '/media/mens-demo/floor-dark-hem-boot-400.webp',
    avifSrcSet: '/media/mens-demo/floor-dark-hem-boot-400.avif 400w',
    webpSrcSet: '/media/mens-demo/floor-dark-hem-boot-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'floor-tan-boots': {
    poster: '/media/mens-demo/floor-tan-boots-540.webp',
    avifSrcSet:
      '/media/mens-demo/floor-tan-boots-480.avif 480w, /media/mens-demo/floor-tan-boots-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/floor-tan-boots-480.webp 480w, /media/mens-demo/floor-tan-boots-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'floor-cream-seated': {
    poster: '/media/mens-demo/floor-cream-seated-400.webp',
    avifSrcSet: '/media/mens-demo/floor-cream-seated-400.avif 400w',
    webpSrcSet: '/media/mens-demo/floor-cream-seated-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'floor-light-jean-side': {
    poster: '/media/mens-demo/floor-light-jean-side-920.webp',
    avifSrcSet:
      '/media/mens-demo/floor-light-jean-side-480.avif 480w, /media/mens-demo/floor-light-jean-side-920.avif 920w',
    webpSrcSet:
      '/media/mens-demo/floor-light-jean-side-480.webp 480w, /media/mens-demo/floor-light-jean-side-920.webp 920w',
    intrinsicWidth: 920,
    intrinsicHeight: 1150,
  },
  'floor-dark-jean-street': {
    poster: '/media/mens-demo/floor-dark-jean-street-536.webp',
    avifSrcSet:
      '/media/mens-demo/floor-dark-jean-street-480.avif 480w, /media/mens-demo/floor-dark-jean-street-536.avif 536w',
    webpSrcSet:
      '/media/mens-demo/floor-dark-jean-street-480.webp 480w, /media/mens-demo/floor-dark-jean-street-536.webp 536w',
    intrinsicWidth: 536,
    intrinsicHeight: 670,
  },
  'floor-denim-texture': {
    poster: '/media/mens-demo/floor-denim-texture-720.webp',
    avifSrcSet:
      '/media/mens-demo/floor-denim-texture-480.avif 480w, /media/mens-demo/floor-denim-texture-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/floor-denim-texture-480.webp 480w, /media/mens-demo/floor-denim-texture-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 720,
  },
  'floor-black-toe': {
    poster: '/media/mens-demo/floor-black-toe-400.webp',
    avifSrcSet: '/media/mens-demo/floor-black-toe-400.avif 400w',
    webpSrcSet: '/media/mens-demo/floor-black-toe-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'floor-cuffing-barn': {
    poster: '/media/mens-demo/floor-cuffing-barn-400.webp',
    avifSrcSet: '/media/mens-demo/floor-cuffing-barn-400.avif 400w',
    webpSrcSet: '/media/mens-demo/floor-cuffing-barn-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'floor-light-jean-worn': {
    poster: '/media/mens-demo/floor-light-jean-worn-540.webp',
    avifSrcSet:
      '/media/mens-demo/floor-light-jean-worn-480.avif 480w, /media/mens-demo/floor-light-jean-worn-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/floor-light-jean-worn-480.webp 480w, /media/mens-demo/floor-light-jean-worn-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'floor-brown-boots': {
    poster: '/media/mens-demo/floor-brown-boots-540.webp',
    avifSrcSet:
      '/media/mens-demo/floor-brown-boots-480.avif 480w, /media/mens-demo/floor-brown-boots-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/floor-brown-boots-480.webp 480w, /media/mens-demo/floor-brown-boots-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'floor-boot-floorboards': {
    poster: '/media/mens-demo/floor-boot-floorboards-400.webp',
    avifSrcSet: '/media/mens-demo/floor-boot-floorboards-400.avif 400w',
    webpSrcSet: '/media/mens-demo/floor-boot-floorboards-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'floor-back-pocket': {
    poster: '/media/mens-demo/floor-back-pocket-720.webp',
    avifSrcSet:
      '/media/mens-demo/floor-back-pocket-480.avif 480w, /media/mens-demo/floor-back-pocket-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/floor-back-pocket-480.webp 480w, /media/mens-demo/floor-back-pocket-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'floor-waist-detail': {
    poster: '/media/mens-demo/floor-waist-detail-720.webp',
    avifSrcSet:
      '/media/mens-demo/floor-waist-detail-480.avif 480w, /media/mens-demo/floor-waist-detail-720.avif 720w',
    webpSrcSet:
      '/media/mens-demo/floor-waist-detail-480.webp 480w, /media/mens-demo/floor-waist-detail-720.webp 720w',
    intrinsicWidth: 720,
    intrinsicHeight: 900,
  },
  'floor-boot-rocks': {
    poster: '/media/mens-demo/floor-boot-rocks-400.webp',
    avifSrcSet: '/media/mens-demo/floor-boot-rocks-400.avif 400w',
    webpSrcSet: '/media/mens-demo/floor-boot-rocks-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'floor-light-jean-flat': {
    poster: '/media/mens-demo/floor-light-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/floor-light-jean-flat-480.avif 480w, /media/mens-demo/floor-light-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/floor-light-jean-flat-480.webp 480w, /media/mens-demo/floor-light-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'floor-boot-crate': {
    poster: '/media/mens-demo/floor-boot-crate-400.webp',
    avifSrcSet: '/media/mens-demo/floor-boot-crate-400.avif 400w',
    webpSrcSet: '/media/mens-demo/floor-boot-crate-400.webp 400w',
    intrinsicWidth: 400,
    intrinsicHeight: 500,
  },
  'floor-pale-jean-flat': {
    poster: '/media/mens-demo/floor-pale-jean-flat-540.webp',
    avifSrcSet:
      '/media/mens-demo/floor-pale-jean-flat-480.avif 480w, /media/mens-demo/floor-pale-jean-flat-540.avif 540w',
    webpSrcSet:
      '/media/mens-demo/floor-pale-jean-flat-480.webp 480w, /media/mens-demo/floor-pale-jean-flat-540.webp 540w',
    intrinsicWidth: 540,
    intrinsicHeight: 675,
  },
  'campaign-hero-mobile': {
    poster: '/media/mens-demo/campaign-hero-mobile-960.webp',
    avifSrcSet:
      '/media/mens-demo/campaign-hero-mobile-480.avif 480w, /media/mens-demo/campaign-hero-mobile-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/campaign-hero-mobile-480.webp 480w, /media/mens-demo/campaign-hero-mobile-960.webp 960w',
    intrinsicWidth: 1122,
    intrinsicHeight: 1402,
  },
  'campaign-story-inset': {
    poster: '/media/mens-demo/campaign-story-inset-960.webp',
    avifSrcSet:
      '/media/mens-demo/campaign-story-inset-480.avif 480w, /media/mens-demo/campaign-story-inset-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/campaign-story-inset-480.webp 480w, /media/mens-demo/campaign-story-inset-960.webp 960w',
    intrinsicWidth: 1122,
    intrinsicHeight: 1402,
  },
  'campaign-story-lead': {
    poster: '/media/mens-demo/campaign-story-lead-960.webp',
    avifSrcSet:
      '/media/mens-demo/campaign-story-lead-480.avif 480w, /media/mens-demo/campaign-story-lead-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/campaign-story-lead-480.webp 480w, /media/mens-demo/campaign-story-lead-960.webp 960w',
    intrinsicWidth: 1122,
    intrinsicHeight: 1402,
  },
  'campaign-world-tile': {
    poster: '/media/mens-demo/campaign-world-tile-960.webp',
    avifSrcSet:
      '/media/mens-demo/campaign-world-tile-480.avif 480w, /media/mens-demo/campaign-world-tile-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/campaign-world-tile-480.webp 480w, /media/mens-demo/campaign-world-tile-960.webp 960w',
    intrinsicWidth: 1122,
    intrinsicHeight: 1402,
  },
  'dark-rigid-jean-back': {
    poster: '/media/mens-demo/dark-rigid-jean-back-960.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-back-480.avif 480w, /media/mens-demo/dark-rigid-jean-back-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-back-480.webp 480w, /media/mens-demo/dark-rigid-jean-back-960.webp 960w',
    intrinsicWidth: 1086,
    intrinsicHeight: 1448,
  },
  'dark-rigid-jean-hem': {
    poster: '/media/mens-demo/dark-rigid-jean-hem-960.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-hem-480.avif 480w, /media/mens-demo/dark-rigid-jean-hem-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-hem-480.webp 480w, /media/mens-demo/dark-rigid-jean-hem-960.webp 960w',
    intrinsicWidth: 1086,
    intrinsicHeight: 1448,
  },
  'dark-rigid-jean-model': {
    poster: '/media/mens-demo/dark-rigid-jean-model-960.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-model-480.avif 480w, /media/mens-demo/dark-rigid-jean-model-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-model-480.webp 480w, /media/mens-demo/dark-rigid-jean-model-960.webp 960w',
    intrinsicWidth: 1086,
    intrinsicHeight: 1448,
  },
  'dark-rigid-jean-motion': {
    poster: '/media/mens-demo/dark-rigid-jean-motion-960.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-motion-480.avif 480w, /media/mens-demo/dark-rigid-jean-motion-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-motion-480.webp 480w, /media/mens-demo/dark-rigid-jean-motion-960.webp 960w',
    intrinsicWidth: 1122,
    intrinsicHeight: 1402,
  },
  'dark-rigid-jean-stack': {
    poster: '/media/mens-demo/dark-rigid-jean-stack-960.webp',
    avifSrcSet:
      '/media/mens-demo/dark-rigid-jean-stack-480.avif 480w, /media/mens-demo/dark-rigid-jean-stack-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/dark-rigid-jean-stack-480.webp 480w, /media/mens-demo/dark-rigid-jean-stack-960.webp 960w',
    intrinsicWidth: 1448,
    intrinsicHeight: 1086,
  },
  'mid-wash-jean-back': {
    poster: '/media/mens-demo/mid-wash-jean-back-960.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-back-480.avif 480w, /media/mens-demo/mid-wash-jean-back-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-back-480.webp 480w, /media/mens-demo/mid-wash-jean-back-960.webp 960w',
    intrinsicWidth: 1086,
    intrinsicHeight: 1448,
  },
  'mid-wash-jean-macro': {
    poster: '/media/mens-demo/mid-wash-jean-macro-960.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-macro-480.avif 480w, /media/mens-demo/mid-wash-jean-macro-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-macro-480.webp 480w, /media/mens-demo/mid-wash-jean-macro-960.webp 960w',
    intrinsicWidth: 1254,
    intrinsicHeight: 1254,
  },
  'mid-wash-jean-motion': {
    poster: '/media/mens-demo/mid-wash-jean-motion-960.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-motion-480.avif 480w, /media/mens-demo/mid-wash-jean-motion-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-motion-480.webp 480w, /media/mens-demo/mid-wash-jean-motion-960.webp 960w',
    intrinsicWidth: 1122,
    intrinsicHeight: 1402,
  },
  'mid-wash-jean-side': {
    poster: '/media/mens-demo/mid-wash-jean-side-960.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-side-480.avif 480w, /media/mens-demo/mid-wash-jean-side-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-side-480.webp 480w, /media/mens-demo/mid-wash-jean-side-960.webp 960w',
    intrinsicWidth: 1086,
    intrinsicHeight: 1448,
  },
  'mid-wash-jean-stack': {
    poster: '/media/mens-demo/mid-wash-jean-stack-960.webp',
    avifSrcSet:
      '/media/mens-demo/mid-wash-jean-stack-480.avif 480w, /media/mens-demo/mid-wash-jean-stack-960.avif 960w',
    webpSrcSet:
      '/media/mens-demo/mid-wash-jean-stack-480.webp 480w, /media/mens-demo/mid-wash-jean-stack-960.webp 960w',
    intrinsicWidth: 1448,
    intrinsicHeight: 1086,
  },
}
