/**
 * GENERATED by scripts/import-campaign-plates.mjs — do not edit by hand.
 * Curated atmosphere plates from the Stitch mirror; see the script for the review rules.
 */

export type PlateAsset = {
  readonly poster: string
  readonly avifSrcSet: string
  readonly webpSrcSet: string
  readonly intrinsicWidth: number
  readonly intrinsicHeight: number
}

export const PLATE_ASSETS = {
  'leather-bench': {
    poster: '/media/campaign/leather-bench-960.webp',
    avifSrcSet:
      '/media/campaign/leather-bench-480.avif 480w, /media/campaign/leather-bench-960.avif 960w, /media/campaign/leather-bench-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/leather-bench-480.webp 480w, /media/campaign/leather-bench-960.webp 960w, /media/campaign/leather-bench-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'tooled-leather': {
    poster: '/media/campaign/tooled-leather-960.webp',
    avifSrcSet:
      '/media/campaign/tooled-leather-480.avif 480w, /media/campaign/tooled-leather-960.avif 960w, /media/campaign/tooled-leather-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/tooled-leather-480.webp 480w, /media/campaign/tooled-leather-960.webp 960w, /media/campaign/tooled-leather-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'indigo-thread': {
    poster: '/media/campaign/indigo-thread-960.webp',
    avifSrcSet:
      '/media/campaign/indigo-thread-480.avif 480w, /media/campaign/indigo-thread-960.avif 960w, /media/campaign/indigo-thread-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/indigo-thread-480.webp 480w, /media/campaign/indigo-thread-960.webp 960w, /media/campaign/indigo-thread-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'embossed-leather': {
    poster: '/media/campaign/embossed-leather-960.webp',
    avifSrcSet:
      '/media/campaign/embossed-leather-480.avif 480w, /media/campaign/embossed-leather-960.avif 960w, /media/campaign/embossed-leather-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/embossed-leather-480.webp 480w, /media/campaign/embossed-leather-960.webp 960w, /media/campaign/embossed-leather-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'denim-weave': {
    poster: '/media/campaign/denim-weave-960.webp',
    avifSrcSet:
      '/media/campaign/denim-weave-480.avif 480w, /media/campaign/denim-weave-960.avif 960w, /media/campaign/denim-weave-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/denim-weave-480.webp 480w, /media/campaign/denim-weave-960.webp 960w, /media/campaign/denim-weave-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'selvedge-beam': {
    poster: '/media/campaign/selvedge-beam-960.webp',
    avifSrcSet:
      '/media/campaign/selvedge-beam-480.avif 480w, /media/campaign/selvedge-beam-960.avif 960w, /media/campaign/selvedge-beam-1376.avif 1376w',
    webpSrcSet:
      '/media/campaign/selvedge-beam-480.webp 480w, /media/campaign/selvedge-beam-960.webp 960w, /media/campaign/selvedge-beam-1376.webp 1376w',
    intrinsicWidth: 1376,
    intrinsicHeight: 768,
  },
  'buckle-denim': {
    poster: '/media/campaign/buckle-denim-768.webp',
    avifSrcSet:
      '/media/campaign/buckle-denim-480.avif 480w, /media/campaign/buckle-denim-768.avif 768w',
    webpSrcSet:
      '/media/campaign/buckle-denim-480.webp 480w, /media/campaign/buckle-denim-768.webp 768w',
    intrinsicWidth: 768,
    intrinsicHeight: 1376,
  },
  'hardware-bench': {
    poster: '/media/campaign/hardware-bench-960.webp',
    avifSrcSet:
      '/media/campaign/hardware-bench-480.avif 480w, /media/campaign/hardware-bench-960.avif 960w, /media/campaign/hardware-bench-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/hardware-bench-480.webp 480w, /media/campaign/hardware-bench-960.webp 960w, /media/campaign/hardware-bench-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'longhorn-buckle': {
    poster: '/media/campaign/longhorn-buckle-960.webp',
    avifSrcSet:
      '/media/campaign/longhorn-buckle-480.avif 480w, /media/campaign/longhorn-buckle-960.avif 960w, /media/campaign/longhorn-buckle-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/longhorn-buckle-480.webp 480w, /media/campaign/longhorn-buckle-960.webp 960w, /media/campaign/longhorn-buckle-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'high-dunes': {
    poster: '/media/campaign/high-dunes-960.webp',
    avifSrcSet:
      '/media/campaign/high-dunes-480.avif 480w, /media/campaign/high-dunes-960.avif 960w, /media/campaign/high-dunes-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/high-dunes-480.webp 480w, /media/campaign/high-dunes-960.webp 960w, /media/campaign/high-dunes-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'pearl-snaps': {
    poster: '/media/campaign/pearl-snaps-960.webp',
    avifSrcSet:
      '/media/campaign/pearl-snaps-480.avif 480w, /media/campaign/pearl-snaps-960.avif 960w, /media/campaign/pearl-snaps-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/pearl-snaps-480.webp 480w, /media/campaign/pearl-snaps-960.webp 960w, /media/campaign/pearl-snaps-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'selvedge-stitch': {
    poster: '/media/campaign/selvedge-stitch-960.webp',
    avifSrcSet:
      '/media/campaign/selvedge-stitch-480.avif 480w, /media/campaign/selvedge-stitch-960.avif 960w, /media/campaign/selvedge-stitch-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/selvedge-stitch-480.webp 480w, /media/campaign/selvedge-stitch-960.webp 960w, /media/campaign/selvedge-stitch-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'night-set': {
    poster: '/media/campaign/night-set-960.webp',
    avifSrcSet:
      '/media/campaign/night-set-480.avif 480w, /media/campaign/night-set-960.avif 960w, /media/campaign/night-set-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/night-set-480.webp 480w, /media/campaign/night-set-960.webp 960w, /media/campaign/night-set-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'khaki-twill': {
    poster: '/media/campaign/khaki-twill-960.webp',
    avifSrcSet:
      '/media/campaign/khaki-twill-480.avif 480w, /media/campaign/khaki-twill-960.avif 960w, /media/campaign/khaki-twill-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/khaki-twill-480.webp 480w, /media/campaign/khaki-twill-960.webp 960w, /media/campaign/khaki-twill-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'warehouse-aisle': {
    poster: '/media/campaign/warehouse-aisle-960.webp',
    avifSrcSet:
      '/media/campaign/warehouse-aisle-480.avif 480w, /media/campaign/warehouse-aisle-960.avif 960w, /media/campaign/warehouse-aisle-1376.avif 1376w',
    webpSrcSet:
      '/media/campaign/warehouse-aisle-480.webp 480w, /media/campaign/warehouse-aisle-960.webp 960w, /media/campaign/warehouse-aisle-1376.webp 1376w',
    intrinsicWidth: 1376,
    intrinsicHeight: 768,
  },
  'felt-hat': {
    poster: '/media/campaign/felt-hat-960.webp',
    avifSrcSet:
      '/media/campaign/felt-hat-480.avif 480w, /media/campaign/felt-hat-960.avif 960w, /media/campaign/felt-hat-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/felt-hat-480.webp 480w, /media/campaign/felt-hat-960.webp 960w, /media/campaign/felt-hat-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'tan-belt': {
    poster: '/media/campaign/tan-belt-960.webp',
    avifSrcSet:
      '/media/campaign/tan-belt-480.avif 480w, /media/campaign/tan-belt-960.avif 960w, /media/campaign/tan-belt-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/tan-belt-480.webp 480w, /media/campaign/tan-belt-960.webp 960w, /media/campaign/tan-belt-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'engraved-buckle': {
    poster: '/media/campaign/engraved-buckle-960.webp',
    avifSrcSet:
      '/media/campaign/engraved-buckle-480.avif 480w, /media/campaign/engraved-buckle-960.avif 960w, /media/campaign/engraved-buckle-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/engraved-buckle-480.webp 480w, /media/campaign/engraved-buckle-960.webp 960w, /media/campaign/engraved-buckle-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'rawhide-tools': {
    poster: '/media/campaign/rawhide-tools-960.webp',
    avifSrcSet:
      '/media/campaign/rawhide-tools-480.avif 480w, /media/campaign/rawhide-tools-960.avif 960w, /media/campaign/rawhide-tools-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/rawhide-tools-480.webp 480w, /media/campaign/rawhide-tools-960.webp 960w, /media/campaign/rawhide-tools-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'denim-slub': {
    poster: '/media/campaign/denim-slub-960.webp',
    avifSrcSet:
      '/media/campaign/denim-slub-480.avif 480w, /media/campaign/denim-slub-960.avif 960w, /media/campaign/denim-slub-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/denim-slub-480.webp 480w, /media/campaign/denim-slub-960.webp 960w, /media/campaign/denim-slub-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'rack-aisle': {
    poster: '/media/campaign/rack-aisle-960.webp',
    avifSrcSet:
      '/media/campaign/rack-aisle-480.avif 480w, /media/campaign/rack-aisle-960.avif 960w, /media/campaign/rack-aisle-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/rack-aisle-480.webp 480w, /media/campaign/rack-aisle-960.webp 960w, /media/campaign/rack-aisle-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'saddle-stitch': {
    poster: '/media/campaign/saddle-stitch-960.webp',
    avifSrcSet:
      '/media/campaign/saddle-stitch-480.avif 480w, /media/campaign/saddle-stitch-960.avif 960w, /media/campaign/saddle-stitch-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/saddle-stitch-480.webp 480w, /media/campaign/saddle-stitch-960.webp 960w, /media/campaign/saddle-stitch-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'tooled-belt-rock': {
    poster: '/media/campaign/tooled-belt-rock-960.webp',
    avifSrcSet:
      '/media/campaign/tooled-belt-rock-480.avif 480w, /media/campaign/tooled-belt-rock-960.avif 960w, /media/campaign/tooled-belt-rock-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/tooled-belt-rock-480.webp 480w, /media/campaign/tooled-belt-rock-960.webp 960w, /media/campaign/tooled-belt-rock-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'showroom-bench': {
    poster: '/media/campaign/showroom-bench-960.webp',
    avifSrcSet:
      '/media/campaign/showroom-bench-480.avif 480w, /media/campaign/showroom-bench-960.avif 960w, /media/campaign/showroom-bench-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/showroom-bench-480.webp 480w, /media/campaign/showroom-bench-960.webp 960w, /media/campaign/showroom-bench-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'snap-macro': {
    poster: '/media/campaign/snap-macro-960.webp',
    avifSrcSet:
      '/media/campaign/snap-macro-480.avif 480w, /media/campaign/snap-macro-960.avif 960w, /media/campaign/snap-macro-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/snap-macro-480.webp 480w, /media/campaign/snap-macro-960.webp 960w, /media/campaign/snap-macro-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
  'denim-blue': {
    poster: '/media/campaign/denim-blue-960.webp',
    avifSrcSet:
      '/media/campaign/denim-blue-480.avif 480w, /media/campaign/denim-blue-960.avif 960w, /media/campaign/denim-blue-1408.avif 1408w',
    webpSrcSet:
      '/media/campaign/denim-blue-480.webp 480w, /media/campaign/denim-blue-960.webp 960w, /media/campaign/denim-blue-1408.webp 1408w',
    intrinsicWidth: 1408,
    intrinsicHeight: 768,
  },
} as const

export type PlateSlug = keyof typeof PLATE_ASSETS
